#!/bin/bash
# =============================================================================
# GMT plot script for 2D acoustic visualization test
#
# Reads grid_info.txt generated by SEMSWS for exact grid parameters.
# Plots wavefield snapshots and material fields.
#
# Usage:
#   bash plot_gmt.sh [results_dir]
#
# Requirements: GMT 6+
# =============================================================================
set -e

RESULTS=${1:-./results}
OUTDIR=${RESULTS}/figures
mkdir -p ${OUTDIR}

# =============================================================================
# Helper: read grid_info.txt
# =============================================================================
read_grid_info() {
    local infofile=$1
    # Source the key=value pairs (skip comments)
    eval $(grep -v '^#' ${infofile} | grep '=')
}

# =============================================================================
# Material fields (Vp, rho)
# =============================================================================
plot_material() {
    local GMT_DIR="${RESULTS}/material/gmt"
    local INFO="${GMT_DIR}/grid_info.txt"

    if [ ! -f "${INFO}" ]; then
        echo "  No material grid_info.txt found"
        return
    fi

    read_grid_info ${INFO}
    echo "  Grid: ${nx}x${ny}, region=${region}, spacing=${spacing}"

    for field in vp rho; do
        local INPUT="${GMT_DIR}/${field}.xyz"
        if [ ! -f "${INPUT}" ]; then
            echo "  Skipping ${field}: file not found"
            continue
        fi

        local GRD="${OUTDIR}/${field}.grd"
        local FIG="${OUTDIR}/${field}"

        gmt xyz2grd ${INPUT} -G${GRD} -R${region} -I${spacing}

        # Check if field is constant (range < 0.1% of mean)
        local ZMIN=$(gmt grdinfo ${GRD} -Cn -o4)
        local ZMAX=$(gmt grdinfo ${GRD} -Cn -o5)
        local IS_CONST=$(awk "BEGIN{m=(${ZMAX}+${ZMIN})/2; s=${ZMAX}-${ZMIN}; print (m!=0 && s/m<0.001) ? 1 : 0}")
        local ZMEAN=$(awk "BEGIN{printf \"%.6g\", (${ZMAX}+${ZMIN})/2}")

        gmt begin ${FIG} png
            if [ "${IS_CONST}" = "1" ]; then
                # Constant field: uniform color, value in title and colorbar
                local CVAL=$(awk "BEGIN{v=${ZMEAN}; printf \"%.6g\", v-1}")
                local CVAL2=$(awk "BEGIN{v=${ZMEAN}; printf \"%.6g\", v+1}")
                gmt makecpt -Cviridis -T${CVAL}/${CVAL2}
                gmt grdimage ${GRD} -R${region} -JX15c/7.5c -C
                gmt basemap -Bxa200f100+l"X (m)" -Bya100f50+l"Y (m)" -BWSne
                gmt colorbar -DJBC+w12c/0.4c+o0/1c -B+l"${field}"
            else
                gmt grdimage ${GRD} -R${region} -JX15c/7.5c -Cviridis
                gmt basemap -Bxa200f100+l"X (m)" -Bya100f50+l"Y (m)" -BWSne
                gmt colorbar -DJBC+w12c/0.4c+o0/1c -Baf+l"${field}"
            fi
        gmt end

        echo "  ${field} -> ${FIG}.png"
    done
}

# =============================================================================
# Wavefield snapshots (pressure)
# =============================================================================
plot_wavefield() {
    local GMT_DIR="${RESULTS}/wavefield/gmt"
    local INFO="${GMT_DIR}/grid_info.txt"

    if [ ! -f "${INFO}" ]; then
        echo "  No wavefield grid_info.txt found"
        return
    fi

    read_grid_info ${INFO}
    echo "  Grid: ${nx}x${ny}, region=${region}, spacing=${spacing}"

    local WFFILES=$(ls ${GMT_DIR}/PS_*.xyz 2>/dev/null | sort)
    if [ -z "${WFFILES}" ]; then
        echo "  No wavefield GMT files found"
        return
    fi

    # Symmetric color range from all snapshots
    local VMAX=$(awk '{if($3!="NaN" && $3+0!=0) v=($3<0?-$3:$3); if(v>m) m=v} END{print m}' ${GMT_DIR}/PS_*.xyz)
    if [ -z "${VMAX}" ] || [ "${VMAX}" = "0" ]; then
        VMAX=1
    fi
    echo "  Max amplitude: ${VMAX}"

    for XYZFILE in ${WFFILES}; do
        local BASENAME=$(basename ${XYZFILE} .xyz)
        local STEP=$(echo ${BASENAME} | sed 's/PS_//')
        local GRD="${OUTDIR}/${BASENAME}.grd"
        local FIG="${OUTDIR}/${BASENAME}"

        gmt xyz2grd ${XYZFILE} -G${GRD} -R${region} -I${spacing}

        gmt begin ${FIG} png
            gmt makecpt -Cpolar -T-${VMAX}/${VMAX} -Z
            gmt grdimage ${GRD} -R${region} -JX15c/7.5c -C
            gmt basemap -Bxa200f100+l"X (m)" -Bya100f50+l"Y (m)" -BWSne
            gmt colorbar -DJBC+w12c/0.4c+o0/1c -Baf+l"Pressure (Pa)"
        gmt end

        echo "  ${BASENAME} -> ${FIG}.png"
    done
}

echo "Plotting material fields..."
plot_material

echo "Plotting wavefield snapshots..."
plot_wavefield

echo "Done. Figures saved to ${OUTDIR}/"
