/**
 * @file partition_mesh.cpp
 * @brief Tool to partition a serial mesh into multiple files for memory-efficient loading
 *
 * This tool creates pre-partitioned mesh files that can be loaded by SEMSWS
 * with mesh.type: partitioned configuration. Each MPI rank will read only
 * its own partition file, reducing memory usage from O(N) to O(N/P).
 *
 * Usage:
 *   # Partition external mesh file
 *   ./partition_mesh -n 64 mesh.gmsh output_dir/
 *
 *   # Generate and partition internal Cartesian mesh
 *   ./partition_mesh -n 64 --internal --size 1000,500,500 --elements 100,50,50 output_dir/
 *
 *   # With Cartesian partitioning (no METIS required)
 *   ./partition_mesh -n 64 -p cartesian -g 4,4,4 mesh.gmsh output_dir/
 */

#include <mfem.hpp>
#include <fstream>
#include <iostream>
#include <sstream>
#include <iomanip>
#include <cstring>
#include <sys/stat.h>

using namespace mfem;

void PrintUsage(const char* prog) {
    std::cout << "Usage: " << prog << " [options] <mesh_file> <output_dir>\n"
              << "       " << prog << " [options] --internal <output_dir>\n\n"
              << "Options:\n"
              << "  -n <nparts>        Number of partitions (required)\n"
              << "  -p <method>        Partitioning method: 'metis' (default) or 'cartesian'\n"
              << "  -g <nx,ny,nz>      Cartesian partition grid (required if -p cartesian)\n"
              << "  -h, --help         Show this help message\n\n"
              << "Output files: mesh.mesh.000000, mesh.mesh.000001, ...\n\n"
              << "Internal mesh options (used with --internal):\n"
              << "  --dim <2|3>        Dimension (default: 3)\n"
              << "  --origin <x,y,z>   Origin coordinates (default: 0,0,0)\n"
              << "  --size <lx,ly,lz>  Domain size (required with --internal)\n"
              << "  --elements <nx,ny,nz>  Number of elements (required with --internal)\n\n"
              << "Examples:\n"
              << "  # Partition Gmsh mesh into 64 parts using METIS\n"
              << "  " << prog << " -n 64 domain.msh partitions/\n\n"
              << "  # Generate and partition 3D Cartesian mesh\n"
              << "  " << prog << " -n 64 --internal --size 1000,500,500 --elements 100,50,50 partitions/\n\n"
              << "  # Use Cartesian partitioning (4x4x4 = 64 parts)\n"
              << "  " << prog << " -n 64 -p cartesian -g 4,4,4 domain.msh partitions/\n";
}

bool ParseIntArray(const char* str, int* arr, int size) {
    char* copy = strdup(str);
    char* token = strtok(copy, ",");
    for (int i = 0; i < size && token; i++) {
        arr[i] = atoi(token);
        token = strtok(nullptr, ",");
    }
    free(copy);
    return true;
}

bool ParseRealArray(const char* str, real_t* arr, int size) {
    char* copy = strdup(str);
    char* token = strtok(copy, ",");
    for (int i = 0; i < size && token; i++) {
        arr[i] = atof(token);
        token = strtok(nullptr, ",");
    }
    free(copy);
    return true;
}

bool DirectoryExists(const std::string& path) {
    struct stat info;
    return stat(path.c_str(), &info) == 0 && (info.st_mode & S_IFDIR);
}

bool CreateDirectory(const std::string& path) {
    return mkdir(path.c_str(), 0755) == 0 || errno == EEXIST;
}

void WritePartitionInfo(const std::string& output_dir, int nparts,
                        const std::string& method,
                        bool use_internal, const Mesh& mesh,
                        const int* partition_grid) {
    std::string info_file = output_dir + "/partition_info.yaml";
    std::ofstream ofs(info_file);

    ofs << "# Partition info generated by partition_mesh tool\n";
    ofs << "partition:\n";
    ofs << "  nparts: " << nparts << "\n";
    ofs << "  method: " << method << "\n";
    if (method == "cartesian" && partition_grid) {
        int dim = mesh.Dimension();
        ofs << "  partition_grid: [" << partition_grid[0];
        for (int i = 1; i < dim; i++) ofs << ", " << partition_grid[i];
        ofs << "]\n";
    }
    ofs << "\nmesh:\n";
    ofs << "  dimension: " << mesh.Dimension() << "\n";
    ofs << "  num_elements: " << mesh.GetNE() << "\n";
    ofs << "  num_vertices: " << mesh.GetNV() << "\n";
    ofs << "  source: " << (use_internal ? "internal" : "external") << "\n";

    ofs.close();
    std::cout << "Wrote partition info to: " << info_file << std::endl;
}

int main(int argc, char* argv[]) {
    // Default values
    int nparts = 0;
    std::string method = "metis";
    int partition_grid[3] = {1, 1, 1};
    bool use_cartesian_partition = false;

    // Internal mesh options
    bool use_internal = false;
    int dim = 3;
    real_t origin[3] = {0.0, 0.0, 0.0};
    real_t size[3] = {0.0, 0.0, 0.0};
    int elements[3] = {0, 0, 0};

    // Element attribute threshold
    real_t attr_y_threshold = -1e30;
    bool attr_y_set = false;

    std::string input_file;
    std::string output_dir;

    // Parse command line
    for (int i = 1; i < argc; i++) {
        std::string arg = argv[i];

        if (arg == "-h" || arg == "--help") {
            PrintUsage(argv[0]);
            return 0;
        } else if (arg == "-n" && i + 1 < argc) {
            nparts = atoi(argv[++i]);
        } else if (arg == "-p" && i + 1 < argc) {
            method = argv[++i];
            use_cartesian_partition = (method == "cartesian");
        } else if (arg == "-g" && i + 1 < argc) {
            ParseIntArray(argv[++i], partition_grid, 3);
        } else if (arg == "--internal") {
            use_internal = true;
        } else if (arg == "--dim" && i + 1 < argc) {
            dim = atoi(argv[++i]);
        } else if (arg == "--origin" && i + 1 < argc) {
            ParseRealArray(argv[++i], origin, 3);
        } else if (arg == "--size" && i + 1 < argc) {
            ParseRealArray(argv[++i], size, 3);
        } else if (arg == "--elements" && i + 1 < argc) {
            ParseIntArray(argv[++i], elements, 3);
        } else if (arg == "--attr-y-threshold" && i + 1 < argc) {
            attr_y_threshold = atof(argv[++i]);
            attr_y_set = true;
        } else if (arg[0] != '-') {
            if (use_internal) {
                output_dir = arg;
            } else if (input_file.empty()) {
                input_file = arg;
            } else {
                output_dir = arg;
            }
        } else {
            std::cerr << "Unknown option: " << arg << std::endl;
            PrintUsage(argv[0]);
            return 1;
        }
    }

    // Validate arguments
    if (nparts < 1) {
        std::cerr << "Error: Number of partitions (-n) is required and must be >= 1\n";
        return 1;
    }

    if (output_dir.empty()) {
        std::cerr << "Error: Output directory is required\n";
        return 1;
    }

    if (!use_internal && input_file.empty()) {
        std::cerr << "Error: Input mesh file is required (or use --internal)\n";
        return 1;
    }

    if (use_internal) {
        if (size[0] <= 0 || size[1] <= 0 || (dim == 3 && size[2] <= 0)) {
            std::cerr << "Error: --size is required with --internal\n";
            return 1;
        }
        if (elements[0] <= 0 || elements[1] <= 0 || (dim == 3 && elements[2] <= 0)) {
            std::cerr << "Error: --elements is required with --internal\n";
            return 1;
        }
    }

    if (use_cartesian_partition) {
        int total = partition_grid[0] * partition_grid[1];
        if (dim == 3) total *= partition_grid[2];
        if (total != nparts) {
            std::cerr << "Error: partition_grid product (" << total
                      << ") must equal nparts (" << nparts << ")\n";
            return 1;
        }
    }

    // Create output directory
    if (!DirectoryExists(output_dir)) {
        if (!CreateDirectory(output_dir)) {
            std::cerr << "Error: Cannot create output directory: " << output_dir << std::endl;
            return 1;
        }
    }

    // Create or load mesh
    Mesh* mesh = nullptr;

    if (use_internal) {
        std::cout << "Generating internal " << dim << "D Cartesian mesh..." << std::endl;
        std::cout << "  Size: [" << size[0] << ", " << size[1];
        if (dim == 3) std::cout << ", " << size[2];
        std::cout << "]" << std::endl;
        std::cout << "  Elements: [" << elements[0] << ", " << elements[1];
        if (dim == 3) std::cout << ", " << elements[2];
        std::cout << "]" << std::endl;

        if (dim == 2) {
            mesh = new Mesh(Mesh::MakeCartesian2D(
                elements[0], elements[1],
                Element::QUADRILATERAL, true, size[0], size[1]));
        } else {
            mesh = new Mesh(Mesh::MakeCartesian3D(
                elements[0], elements[1], elements[2],
                Element::HEXAHEDRON, size[0], size[1], size[2]));
        }

        // Apply origin offset
        if (origin[0] != 0.0 || origin[1] != 0.0 || (dim == 3 && origin[2] != 0.0)) {
            for (int vi = 0; vi < mesh->GetNV(); vi++) {
                real_t* v = mesh->GetVertex(vi);
                for (int d = 0; d < dim; d++) {
                    v[d] += origin[d];
                }
            }
            std::cout << "  Origin offset: [" << origin[0] << ", " << origin[1];
            if (dim == 3) std::cout << ", " << origin[2];
            std::cout << "]" << std::endl;
        }
    } else {
        std::cout << "Loading mesh from: " << input_file << std::endl;
        mesh = new Mesh(input_file.c_str(), 1, 1);
        dim = mesh->Dimension();
    }

    std::cout << "Mesh: " << mesh->GetNE() << " elements, "
              << mesh->GetNV() << " vertices, dimension " << dim << std::endl;

    // Set element attributes by y-threshold
    if (attr_y_set) {
        int count_above = 0, count_below = 0;
        for (int ie = 0; ie < mesh->GetNE(); ie++) {
            Vector center;
            mesh->GetElementCenter(ie, center);
            if (center(1) >= attr_y_threshold) {
                mesh->SetAttribute(ie, 1);  // above threshold (e.g. water)
                count_above++;
            } else {
                mesh->SetAttribute(ie, 2);  // below threshold (e.g. solid)
                count_below++;
            }
        }
        mesh->SetAttributes();
        std::cout << "Set element attributes by y-threshold " << attr_y_threshold
                  << ": attr=1 (" << count_above << " elems), attr=2 ("
                  << count_below << " elems)" << std::endl;
    }

    // Create partitioning array
    int* partitioning = nullptr;

    if (use_cartesian_partition) {
        std::cout << "Using Cartesian partitioning: ["
                  << partition_grid[0] << ", " << partition_grid[1];
        if (dim == 3) std::cout << ", " << partition_grid[2];
        std::cout << "]" << std::endl;

        partitioning = mesh->CartesianPartitioning(partition_grid);
    } else {
        std::cout << "Using METIS partitioning with " << nparts << " parts" << std::endl;
        // partitioning = nullptr -> MeshPartitioner will use METIS internally
    }

    // Create MeshPartitioner
    std::cout << "Partitioning mesh into " << nparts << " parts..." << std::endl;
    MeshPartitioner partitioner(*mesh, nparts, partitioning);

    // Write each partition
    MeshPart mesh_part;
    for (int r = 0; r < nparts; r++) {
        partitioner.ExtractPart(r, mesh_part);

        std::ostringstream oss;
        oss << output_dir << "/mesh.mesh." << std::setfill('0') << std::setw(6) << r;
        std::string filename = oss.str();

        std::ofstream ofs(filename);
        if (!ofs.good()) {
            std::cerr << "Error: Cannot write to " << filename << std::endl;
            delete[] partitioning;
            delete mesh;
            return 1;
        }
        mesh_part.Print(ofs);
        ofs.close();

        if ((r + 1) % 100 == 0 || r == nparts - 1) {
            std::cout << "  Written " << (r + 1) << "/" << nparts << " partitions\r" << std::flush;
        }
    }
    std::cout << std::endl;

    // Write partition info
    WritePartitionInfo(output_dir, nparts, method, use_internal, *mesh,
                       use_cartesian_partition ? partition_grid : nullptr);

    // Cleanup
    delete[] partitioning;
    delete mesh;

    std::cout << "Done! Partitioned mesh files written to: " << output_dir << "/" << std::endl;
    std::cout << "\nTo use in SEMSWS config:\n";
    std::cout << "  mesh:\n";
    std::cout << "    type: partitioned\n";
    std::cout << "    partitioned:\n";
    std::cout << "      directory: \"" << output_dir << "\"\n";
    std::cout << "      nparts: " << nparts << "\n";

    return 0;
}
